---
title: "Downloads"
---

## Downloads

<!-- The following bio and [**this photo**](/img/zhenkun.jpg) may be used in media releases without further permission. -->

:::: {.columns}

::: {.column width="30%"}

<ul class="fa-ul">
  <li><a href="https://github.com/robjhyndman/CV/raw/master/RobHyndmanCV.pdf"><i class="fa-li fa-regular fa-file-pdf"></i>Curriculum Vitae</a></li>
  <li><a href="https://scholar.google.com/citations?user=vamErfkAAAAJ"><i class="fa-li ai ai-google-scholar" style="padding-top:4px;"></i>Google Scholar</a></li>
  <li><a href="https://www.semanticscholar.org/author/R.-Hyndman/145211352"><i class="fa-li ai ai-semantic-scholar" style="padding-top:4px;"></i>Semantic Scholar</a></li>
</ul>

:::

::: {.column width="30%"}

<ul class="fa-ul">
  <li><a href="https://orcid.org/0000-0002-2140-5352"><i class="fa-li ai ai-orcid" style="padding-top:4px;"></i>ORCID</a></li>
  <li><a href="https://www.scopus.com/authid/detail.uri?authorId=7006914313"><i class="fa-li ai ai-scopus" style="padding-top:4px;"></i>Scopus</a></li>
    <li><a href=https://arxiv.org/a/hyndman_r_1.html><i class="fa-li ai ai-arxiv" style="padding-top:4px;"></i>arXiv</a></li>
</ul>

:::

::: {.column width="30%"}
<ul class="fa-ul">
<li><a href="http://ideas.repec.org/e/phy3.html"><i class="fa-li fa-regular fa-lightbulb"></i>RePEc</a></li>
  <li><a href="https://github.com/robjhyndman"><i class="fa-li fa-brands fa-github"></i>GitHub</a></li>
  <li><a href="http://en.wikipedia.org/wiki/Rob_J._Hyndman"><i class="fa-li fa-brands fa-wikipedia-w"></i>Wikipedia</a></li>
</ul>

:::

::::

## Address

<!-- **Mail:** [Department of Econometrics & Business Statistics](https://monash.edu/business/ebs), [Monash University](https://monash.edu/), Clayton VIC 3800, Australia. -->

**Office:** Room 216, Rakentajanaukio 4 A, [Aalto University](https://www.aalto.fi/en), Espoo 02150, Finland

<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1983.599213680743!2d24.828383713125476!3d60.187365841941535!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x468df5edaf5e8faf%3A0x424cf3b98c2701d6!2sRakentajanaukio%204%2C%2002150%20Espoo!5e0!3m2!1sen!2sfi!4v1686644392933!5m2!1sen!2sfi" width="660" height="480" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
## Education

 * 09.2017-06.2020, M.Eng.,Dalian University of Technology (DUT).
 * 09.2013-06.2017, B. Eng., Qingdao University of Technology (QUT).

## Employment

  * **Project employee**, Department of Civil Engineering, Aalto University, 2021--.

<!-- ## Fellowships -->

<!-- I am a fellow of the following organizations: -->

<!--   * [Australian Academy of Science](https://www.science.org.au/profile/rob-hyndman) -->
<!--   * [Academy of the Social Sciences in Australia](https://socialsciences.org.au/academy-fellow/?sId=0032v00003JxrvjAAB) -->
<!--   * [International Institute of Forecasters](https://forecasters.org/about/fellows/) -->

<!-- ## Society memberships -->

<!--   * Elected member, [International Statistical Institute](http://isi.cbs.nl) -->
<!--   * Member, [International Association for Statistical Computing](http://www.iasc-isi.org) -->
<!--   * Member, [International Association for Statistical Education](https://iase-web.org) -->
<!--   * Member, [International Society for Business and Industrial Statistics](http://isbis-isi.org) -->
<!--   * Member, [Statistical Society of Australia](http://www.statsoc.org.au) -->
<!--   * Member, [Foundation for Open Access Statistics](http://foastat.org/) -->

<!-- ## Society leadership -->

<!--   * Director, [International Institute of Forecasters](https://forecasters.org/), 2005--2018. -->
<!--   * Member, Scientific Program Advisory Group, [Statistical Society of Australia](http://www.statsoc.org.au), 2001--2004 -->
<!--   * Central Council member, [Statistical Society of Australia](http://www.statsoc.org.au), 1993--1996. -->
<!--   * Secretary, Victorian branch, [Statistical Society of Australia](http://www.statsoc.org.au), 1993--1995. -->

<!-- ## Academic and research leadership -->

<!--   * **Head**, Department of Econometrics & Business Statistics, Monash University. 2019--2022. -->
<!--   * **Director**, Business & Economic Forecasting Unit, Monash University. 2001--2017. -->
<!--   * **Director of Consulting**, Econometrics and Business Statistics, Monash University. 2000--2014. -->
<!--   * **Director**, Monash University Statistical Consulting Service, 1997--1998. -->
<!--   * **Director**, Key Centre for Statistical Science, 1996--1998. -->

<!-- ## Editorial boards -->

<!--   * Executive Editor, *[The R Journal](https://rjournal.github.io)* (2023--2026). -->
<!--   * Editor, *[Journal of Statistical Software](http://www.jstatsoft.org/)* (2011--). -->
<!--   * Associate Editor, *[International Journal of Forecasting](http://ijf.forecasters.org/)* (2001--2004,2019--). -->
<!--   * Editor, [NEP forecasting report](http://ideas.repec.org/n/nep-for/) (2005--). -->
<!--   * Editor-in-Chief, *[International Journal of Forecasting](http://ijf.forecasters.org/)* (2005--2018). -->
<!--   * Theory and Methods Editor, *[Australian & New Zealand Journal of Statistics]()* (2001--2004). -->

<!-- ## Advisory boards -->

<!--   * Member of the Scaling committee, [Victorian Tertiary Admissions Centre](http://www.vtac.edu.au). This committee is responsible for producing the [ATAR for VCE students](http://en.wikipedia.org/wiki/Australian_Tertiary_Admission_Rank) (1994--). -->
<!--   * Member of the ATAR Technical Group for the [Australasian Conference of Tertiary Admissions Centres](http://www.actac.edu.au) (2003--). -->
<!--   * Member of the Indigenous Statistical and Information Advisory Group for the [Australian Institute of Health and Welfare](http://www.aihw.gov.au) (2017--). -->
<!--   * Member of the [COVID-19 national situational assessment team](https://mspgh.unimelb.edu.au/research-groups/centre-for-epidemiology-and-biostatistics-research/Infectious-Disease-Dynamics/covid-19-national-situational-assessment) (2020--). -->
<!--   * Member of the Methodology Advisory Committee for the Australian Bureau of Statistics (2010--2018). -->

<!-- ## Conference organization -->

<!--   * Chair, [IIF Workshop on Forecast Reconciliation](/prato2023/index.qmd), 2023. -->
<!--   * General Chair, International Symposium on Forecasting, 2017. -->
<!--   * Program Chair, International Symposium on Forecasting, 2012. -->
<!--   * Program Co-Chair, International Symposium on Forecasting, 2004. -->



## Awards and honours
* [Fabian and Jaakko Ahvenainen Foundation grants awarded for the year 2022](https://www.aalto.fi/en/news/fabian-and-jaakko-ahvenainen-foundation-grants-awarded-for-the-year-2022), Aalto University. 
* Jun. 2020, Excellent master thesis, DUT.
* Jun. 2020, Eminent graduate in Liaoning Province, Liaoning Province.
* Nov. 2019, Scholarship of Chinese Road and Bridge, DUT.
* Oct. 2018, Eminent postgraduate student, DUT.
* Oct. 2016, Scholarship from Province Government (1/508), Shandong Province.
* Dec. 2015, 2nd Prize in National Mathematic Modeling Competition, National.
* Nov. 2015, 3rd Prize in the National Advanced Innovated Competition, National.
* Jun. 2015, 2nd Prize in the 14th Challenge Cup Competition, Shandong Province.
* Nov. 2014, Scholarships from Principal of QUT (4/508), QUT.

<!-- * Australian Awards for University Teaching citation for outstanding contributions to student learning (2022) -->

<!-- * Vice-Chancellor's Award for Innovation in Learning and Teaching (2021) -->
<!-- * MSA Teaching Excellence Award for Business and Economics, Monash Student Association (2020) -->
<!-- * Dean's Award for Innovation in Learning and Teaching, Monash Business School (2020) -->
<!-- * Commendation for the Dean's Award for Research Impact, Monash Business School (2018) -->
<!-- * Nominee for MPA Supervisor of the Year, Monash Postgraduate Association (2014) -->
<!-- * Dean's Award for Excellence in Innovation and External Collaboration, Monash Business School (2010) -->
<!-- * HP Innovation Research Award (2010) -->
<!-- * Dean's Award for Excellence in Research, Monash Business School (2008) -->
<!-- * Vice-Chancellor's Award for Postgraduate Supervisor of the Year, Monash University (2008) -->
<!-- * [Moran Medal for Statistical Science, Australian Academy of Science](https://www.science.org.au/past-winners/2007-awardees#moran) (2007) -->
<!-- * Award for excellence in teaching, Monash Science Society (1998) -->
<!-- * Finalist, Channel Ten Young Achiever Awards (1990) -->
<!-- * Dwights Prize in Statistics, University of Melbourne (1988) -->
<!-- * Norma McArthur Prize in Statistics, University of Melbourne (1987) -->
<!-- * Second Maurice H Belz Prize in Statistics, University of Melbourne (1986) -->

## In the news

Here is a list of [recent news articles about me](../news.qmd).

<!-- ## Trivia -->

<!-- My [mathematical genealogy](/hyndsight/mathematical-genealogy/) goes back to Leibniz, Bernoulli, Euler, Lagrange and Poisson. -->

<!-- My [Erdös number](http://www.oakland.edu/enp/) is 3 in two different ways. -->

<!--   * via Peter Brockwell / Kai-Lai Chung / Paul Erdös -->
<!--   * via J. Keith Ord / Peter C Fishburn / Paul Erdös -->

## Other interests
* Basketball.
* Photography: beginning from undergraduate period.
* Running.

 <!-- * I play tennis for the [Heathmont Parker Reserve Tennis Club](http://www.hprtc.org.au/), and I'm coached by [Ben Longridge](https://www.facebook.com/advantedgetennis/). -->
 <!-- * Previously I played cricket for the [Heathwood Cricket Club](https://www.heathwood.cc/). I'm also an accredited umpire with Cricket Australia. -->

<!-- ## Family websites -->

<!--   * [Leanne Hyndman](https://www.riverbankcounselling.com/) -->
<!--   * [Timothy Hyndman](https://timothyhyndman.com/) -->
<!--   * [Dave Hyndman](https://vimeo.com/davidhyndman) -->
